apiVersion: v1
kind: Service
metadata:
  name: back-end-1
spec:
  selector:
    app: back-end-1
  ports:
  - port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: back-end-1
  template:
    metadata:
      labels:
        app: back-end-1
    spec:
      nodeSelector:
        key: main
      containers:
      - name: back-end-1
        image: niyazidocker/back-end-1
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
